# -- CONFIGURAÇÕES GERAIS --
title: "Dax Style Guide"
description: "Padrões e convenções para construção de dashboards no Microsoft Power BI"
baseurl: "/dax-style-guide" # Vazio p/ githubpages
url: "https://davimmilhome.github.io" 

# -- TEMA --
remote_theme: just-the-docs/just-the-docs
color_scheme: dark

# -- NAVEGAÇÃO --
aux_links:
  "Repositório no GitHub":
    - "https://github.com/davimmilhome/dax-style-guide"

# -- BUILD --
markdown: kramdown
highlighter: rouge
permalink: pretty
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
